CREATE OR REPLACE TRIGGER TRG_CREDIT
BEFORE INSERT or UPDATE
ON CUSTOMER
REFERENCING OLD AS oldrow NEW AS newrow
FOR EACH ROW
DECLARE
BEGIN
		IF (:NEWROW.CREDIT < 0) THEN
   		RAISE_APPLICATION_ERROR(-20999  , 'The Credit can NOT be < 0,
			current Credit ' || :newrow.credit || '!!!');
 	END IF;

END TRG_CREDIT;
